- hosts: localhost
  connection: local
  remote_user: test
  gather_facts: no
  vars_files:
    - data.yml

  tasks:

    - name: clone a repo
      command: git clone https://github.com/Prakshi24/MLIris.git
      command: cd MLIris
      command: python irs.py
      register: pass
    - debug: var=pass.stdout
    - name: acc>acc2
      command: echo hello world
      register: pass2
    - debug: var=pass2.stdout
      when: ((acc) > (acc2))
