- hosts: localhost
  connection: local
  remote_user: test
  gather_facts: no
  vars_files:
    - data.yml

  tasks:

    - name: clone a repo
      command: git clone https://github.com/Prakshi24/MLIris.git

    - name: clone a repo
      command: python MLIris/irs.py
      register: pass

    - debug: var=pass.stdout

- hosts: localhost
  connection: local
  remote_user: test
  gather_facts: no
  vars_files:
    - data.yml

  tasks:

    - name: acc>acc2
      command: echo hello world
      when: acc > acc2
