- hosts: localhost
  connection: local
  remote_user: test
  gather_facts: no
  tasks:

    - name: clone a repo
      command: git clone https://github.com/Prakshi24/MLIris.git

    - name: create data.yml
      command: touch data.yml

- hosts: localhost
  connection: local
  remote_user: test
  gather_facts: no
  vars_files:
    - data.yml
  tasks:

    - name: running Ml script
      command: python MLIris/irs.py
      register: pass
    - debug: var=pass.stdout

    - name: Query Dynamo db
      command: python MLIris/query.py

    - name: acc1>acc2
      command: echo hello world
      when: acc1 > acc2
      register: result
      ignore_errors: True
    - name: on success
      command: "{{item}}"
      with_items:
       - mkdir large-rep
       - touch large-rep/first
       - touch large-rep/second
       - zip -r large-rep.zip large-rep
       - git add large-rep.zip
       - git commit -m "add zip"
       - git pull origin master
       - git push origin master
      when: result|succeeded
